-- ═══════════════════════════════════════════════════════════════════════════
-- 0018_payment_hardening.sql
-- Database-level protection against duplicate charges and duplicate access.
--
-- ⚠ WHAT WAS ALREADY RIGHT, so nobody "fixes" it again:
--     payment_references.stripe_checkout_session_id  unique
--     payment_references.stripe_payment_intent_id    unique
--     payments_idempotency_uniq (user_id, idempotency_key)
--     enrollments_active_uniq (user_id, level) where status = 'active'
--     memberships unique (user_id)
--     stripe_events.id primary key  (Stripe's evt_… is the natural key)
--
-- ⚠ WHY IT ALL FAILED ANYWAY. The idempotency key was generated by the
-- BROWSER — `crypto.randomUUID()` on every click of the Enrol button. Two
-- clicks produced two different keys, so the unique index never fired and two
-- Stripe sessions were created. The constraint was correct and unreachable.
--
-- Fixed in src/lib/stripe/checkout.ts by deriving the key server-side from
-- (user, plan, attempt). This migration adds the constraints that make that
-- derivation safe under concurrency, plus a state machine.
-- ═══════════════════════════════════════════════════════════════════════════

begin;

-- ── 1 · The two missing payment states ────────────────────────────────────
-- Stripe reports both, and without them we cannot distinguish "we are waiting
-- on the bank" from "nothing has happened yet" — which matters because one is
-- retryable and the other is not.
--
-- `if not exists` so this migration is safe to re-run.

alter type public.payment_status add value if not exists 'processing'      after 'pending';
alter type public.payment_status add value if not exists 'requires_action' after 'processing';

commit;  -- enum additions must commit before they can be referenced below

begin;

-- ── 2 · ONE OPEN PAYMENT PER USER PER PLAN ────────────────────────────────
-- ⚠ THIS IS THE CONSTRAINT THAT ACTUALLY STOPS A DOUBLE CHARGE.
--
-- The existing index is on (user_id, idempotency_key), which only helps if the
-- key is stable. This one is on the business key and does not care what the key
-- is: a user cannot have two simultaneously open payments for the same plan,
-- however many times they click.
--
-- Partial, on the open states only, because:
--   · a genuinely FAILED attempt must not block a retry (requirement 7)
--   · a REFUNDED payment must not block re-purchase
--   · multiple historical rows for the same plan are legitimate
--
-- Concurrency: two simultaneous requests both insert; one wins, the other gets
-- 23505 and re-reads the winner's row. That is the only safe pattern — an
-- "check then insert" cannot work because both requests pass the check.

create unique index if not exists payments_one_open_per_plan
  on public.payment_references (user_id, plan_id)
  where status in ('pending', 'processing', 'requires_action');

-- ── 3 · ONE SUCCESSFUL PAYMENT PER USER PER PLAN ──────────────────────────
-- Requirement 8. Even if the open-payment index is somehow bypassed, a second
-- successful charge for the same plan cannot be recorded.
--
-- ⚠ NOT ENFORCED FOR REFUNDS. A refunded payment leaves `paid` and moves to
-- 'refunded', so re-purchase after a refund still works.

create unique index if not exists payments_one_paid_per_plan
  on public.payment_references (user_id, plan_id)
  where status = 'paid';

-- ── 4 · Deterministic idempotency keys must be unique globally ────────────
-- The key now encodes the user, so a plain unique index is equivalent to the
-- existing (user_id, key) one — but it also catches a key collision across
-- users, which would mean the derivation is broken. Cheap tripwire.

create unique index if not exists payments_idempotency_global_uniq
  on public.payment_references (idempotency_key);

-- ── 5 · State machine ─────────────────────────────────────────────────────
-- ⚠ REJECTS BACKWARD TRANSITIONS AT THE DATABASE, not in the application.
-- The specific case this prevents: a late-arriving `payment_intent.failed`
-- webhook overwriting a `paid` row and revoking access the student paid for.
-- Stripe does not guarantee delivery order.

create or replace function public.payment_status_guard()
returns trigger language plpgsql as $$
begin
  if old.status = new.status then return new; end if;

  -- Terminal states. Nothing may move out of them except paid → refund.
  if old.status = 'paid' and new.status not in ('refunded','partially_refunded') then
    raise exception 'invalid payment transition % → % for payment %',
      old.status, new.status, old.id;
  end if;

  if old.status in ('refunded','canceled') then
    raise exception 'payment % is in terminal state %, cannot move to %',
      old.id, old.status, new.status;
  end if;

  /* 'failed' is deliberately NOT terminal: Stripe can report a failed
     payment_intent and then a successful one on the same session when the
     customer corrects their card. */
  return new;
end;
$$;

drop trigger if exists payment_status_guard on public.payment_references;
create trigger payment_status_guard
  before update of status on public.payment_references
  for each row execute function public.payment_status_guard();

-- ── 6 · Webhook event bookkeeping ─────────────────────────────────────────
-- `attempts` already exists and was never incremented, so a repeatedly failing
-- event was indistinguishable from a fresh one.

create index if not exists stripe_events_unprocessed_idx
  on public.stripe_events (received_at)
  where processed_at is null;

comment on column public.stripe_events.processed_at is
  'Null means the event was RECEIVED but not completed. The webhook must treat '
  'a duplicate delivery of an unprocessed event as retryable, NOT as a replay '
  'to acknowledge — that bug stranded a paid purchase on 2026-09-10.';

commit;

-- ── Verification ──────────────────────────────────────────────────────────
--   select indexname from pg_indexes
--    where tablename = 'payment_references' and indexname like 'payments_%';
--   -- expect: payments_idempotency_uniq, payments_one_open_per_plan,
--   --         payments_one_paid_per_plan, payments_idempotency_global_uniq
--
--   select unnest(enum_range(null::public.payment_status));
--   -- expect: pending, processing, requires_action, paid, failed, refunded,
--   --         partially_refunded, canceled
--
-- ⚠ IF payments_one_open_per_plan FAILS TO CREATE, existing rows already
-- violate it — two open payments for the same user and plan. Resolve before
-- retrying:
--
--   select user_id, plan_id, count(*), array_agg(id)
--     from public.payment_references
--    where status in ('pending','processing','requires_action')
--    group by user_id, plan_id having count(*) > 1;
--
-- Cancel the older ones:
--   update public.payment_references set status = 'canceled'
--    where id = '<older-id>';
-- ═══════════════════════════════════════════════════════════════════════════
